[build]
  # Directorio base donde está el código Angular
  base = "sistema-contable"
  
  # Directorio de publicación después del build
  publish = "dist/sistema-contable/browser"
  
  # Comando usando npx para asegurar que ng se encuentre
  command = "npm install --legacy-peer-deps && npx ng build --configuration production"

[build.environment]
  # Versión de Node.js actualizada para Angular 20+
  NODE_VERSION = "20"
  
  # Variables para optimización
  NODE_OPTIONS = "--max-old-space-size=4096"
  CI = "true"

# Redirecciones para Angular Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers básicos
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
