[build]
  # Directorio base donde está el código Angular
  base = "sistema-contable"
  
  # Directorio de publicación después del build
  publish = "dist/sistema-contable/browser"
  
  # Comando de build optimizado para Netlify
  command = "npm ci --legacy-peer-deps --no-audit --no-fund && npm run build:netlify"

[build.environment]
  # Versión de Node.js
  NODE_VERSION = "18"
  
  # Variables para Angular y optimización de memoria
  NODE_ENV = "production"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NPM_FLAGS = "--legacy-peer-deps --no-audit --no-fund"
  CI = "true"

# Redirecciones para Angular Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers para optimización
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000"

# Headers específicos para index.html
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

# Headers para archivos estáticos
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
