[build]
  # Directorio base donde está el código Angular
  base = "sistema-contable"
  
  # Directorio de publicación después del build
  publish = "sistema-contable/dist/sistema-contable/browser"
  
  # Comando de build para Netlify
  command = "npm run build:netlify"

[build.environment]
  # Versión de Node.js
  NODE_VERSION = "18"
  
  # Variables para Angular
  NODE_ENV = "production"

# Redirecciones para Angular Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers para Angular
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000"

# Headers específicos para index.html
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
